### ISSUE TITLE
Expand supported sites (youtube-dl, soundcloud)

### ISSUE THREAD

**Issue by jtagcat** [mxpv/podsync#226] opened 2021-05-28 00:16 UTC
```
time="2021-05-27T22:39:08Z" level=info msg="-> updating https://soundcloud.com/redacted/tracks" feed_id=foo format=audio quality=high
time="2021-05-27T22:39:08Z" level=error msg="failed to update feed: https://soundcloud.com/redacted/tracks" error="update failed: failed to parse URL: https://soundcloud.com/redacted/tracks: unsupported URL host"
```

youtube-dl can handle it just fine.

**Comment by ticky** [comment] 2021-06-02 20:18
this is a duplicate of #175

**Closed** 2021-06-02 20:21 UTC
